.\"
.\"
.\"
.\"
.\"
.\"
.TH DISCUSS SIPB "14 April 1987"
.FM quote "MIT SIPB"
.SH NAME
discuss \- Conferencing system
.SH SYNOPSIS
.B discuss
[ 
.B meeting_name
]
.SH DESCRIPTION
.I Discuss
is a user-interface program to a networked conferencing system.  It
provides the concept of "meetings", which a user may attend.  Users
may post "transactions" (short pieces of text) which may be read out
of the meeting.  The
.I Discuss
user interface is heavily influenced by the Multics
.I Forum
conferencing system.

The commands accepted may be listed by using the "?" command once in
discuss.  There is also a "help" command which provides help on a
command once inside the program.  
Type "help commandname" to get information on using a command.
The "quit" command exits discuss.

For an introduction to using this system, consult the document "Using
Discuss", available from the SIPB.

.SH FILES
.ta \w'/usr/spool/discuss/*  'u
.br
/usr/spool/discuss/*	Meetings
.br
/tmp/mtg#####.#####	Temporary file for editing.
.br
~/.meetings	Data file listing meetings that you attend.

.SH AUTHORS
Stan Zanarotti, Ken Raeburn, Robert French, Bill Sommerfeld, and Ted
Ts'o of the MIT Student Information Processing Board.

.SH "SEE ALSO"
.I "Using Discuss",
available from the SIPB.

.I Multics forum manual
:\-)

.SH BUGS
Many; Let us know about them.  Many of them are documented in the
online helpfiles.




