.\" This is an -*- nroff -*- source file.
.\"
.TH DISSERVE 8 "9 September 2012" "Discuss" "debathena-discuss-server"
.SH NAME
disserve \- local access component of discuss server
.SH SYNOPSIS
.B disserve
.SH DESCRIPTION
The
.B disserve
program is a component of the discuss server.  Is it not intended to be
run by hand.

\fBdisserve\fR is typically installed setuid, owned by the 'discuss'
user, and run (by \fBdiscuss\fR(1) or \fImkds\fR(8), for example) to
handle local access to discuss meetings.

.SH SEE ALSO
.BR discuss (1)
