.\"
.\"
.\"
.\"
.\"
.\"
.TH CRMTGS 1 "16 October 2009" "MIT SIPB"
.SH NAME
crmtgs \- Update a ~/.meetings file with the long name of each meeting
.SH SYNOPSIS
.B crmtgs
.SH DESCRIPTION
.I crmtgs
searches a ~/.meetings file for any meeting specifiers which do not
have their canonical "long name" specified in the file.  If any are
found, they are updated with the canonical long name for the meeting
in question.  
.I crmtgs 
accepts no arguments.

.SH FILES
~/.meetings	Data file listing meetings that you attend.

.SH AUTHORS
Bill Sommerfeld, MIT Student Information Processing Board

.SH "SEE ALSO"
.PP
discuss(1)






